#!/bin/sh

### BEGIN INIT INFO
# Provides:          sniffer-app-ctl
# Required-Start:    #adjust
# Required-Stop:     #adjust
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
 
DESC="WIT App Watchdog Startup Script Deamon"
NAME="wit-watchdog"

case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	wit_watchdog.sh &
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	killall -9 wit_watchdog
	killall -9 sniff
	echo "."
	;;
  restart)
	echo -n "Restarting $DESC: $NAME"
	killall -9 wit_watchdog
	killall -9 sniff
	sleep 1
	wit_watchdog.sh &
	echo "."
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0

